#!/bin/bash

network() {
	wire="$(ip a | grep 'enp3s0f3u2' | grep inet | wc -l)"
	wire2="$(ip a | grep 'usb0' | grep inet | wc -l)"
	wifi="$(ip a | grep wlp1s0 | grep inet | wc -l)"

	if [ $wire = 1 ]; then
	        echo "✅"
       elif [ $wire2 = 1 ]; then
               echo "✅"
       elif [ $wifi = 1 ]; then
   	        echo "✅"
   	   else
	   echo "❌睊"
	fi
}
#  ﴹ  睊  ﯥ ❎✅  🖥️ 💻 🌐  
echo "$(network)"
