#!/bin/bash

# PREFIX_PLAY='⏮️⏯️⏭️' 
# PREFIX_PAUSE='⏮️⏸️⏭️'
PREFIX_PLAY='ﭢ'
PREFIX_PAUSE='ﭢ'

get_mpd()
{
	current_song="$(mpc -p 6601 current | awk '{print substr($0,1,35)}')"

	if [[ "$current_song" = "" ]]; then
		echo ""
		exit 0
	else
		playpause=$(mpc -p 6601 | awk '/\[.*]/{split($0, a, " "); print a[1]}')
		if [[ "$playpause" = "[playing]" ]]; then
			current_song="$PREFIX_PLAY"
		elif [[ "$playpause" = "[paused]" ]]; then
			current_song="$PREFIX_PAUSE"
		fi
	fi
   now_playing="$(mpc -p 6601 current)"
 case $BLOCK_BUTTON in
	1) mpc -p 6601 prev ;;
	2) notify-send "$now_playing" ;;
	3) mpc -p 6601 seek -10 ;;
	# 1) zathura /home/agung/.dwm/help/help.pdf ;;
	# 1) notify-send "❓ Help module" "\- Left click to open LARBS guide. ;;
	# 3) dmenu_run ;;
  # 4) zathura /home/agung/.dwm/help/help.pdf ;;
  # 5) zathura /home/agung/.dwm/help/help.pdf ;;
	# 6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac;

	echo " $current_song"
}
get_mpd
