#!/bin/bash
#Purpose: 
#Version: 
#Created Date:  Sen 04 Apr 2022 03:34:27 WIB
#Modified Date: 
#Author: Agung Satria
# START #
#!/bin/bash
#requires:
# sudo apt install xdotool

IFS='x' read screenWidth screenHeight < <(xdpyinfo | grep dimensions | grep -o '[0-9x]*' | head -n1)

width=$(xdotool getactivewindow getwindowgeometry --shell | head -4 | tail -1 | sed 's/[^0-9]*//')
height=$(xdotool getactivewindow getwindowgeometry --shell | head -5 | tail -1 | sed 's/[^0-9]*//')

newPosX=$((screenWidth/2-width/2))
newPosY=$((screenHeight/2-height/2))

xdotool getactivewindow windowmove "$newPosX" "$newPosY"
# END #
