#!/bin/bash
#Purpose: echo ipv4 eth address
#Version: 
#Created Date:  Mon 15 Nov 2021 05:02:20 AM WIB
#Modified Date: 
#Author: Agung Satria
# START #
# ip="$(ifconfig | grep inet | awk 'NR==3 { print $2 }')"
ip="$(ip a | grep 192 | awk '{ print $2 }')"
ipcheck="$(ip a | grep 192 | awk '{ print $2 }' | awk '{ print substr($0, 1, 3)}')"
if [ "$ipcheck" = "" ]; then
    echo -e "\033[31mNot Connected\033[0m"
else
    echo -e "\033[92m$ip\033[0m"
fi
# END #
