#!/bin/bash

exec xautolock -detectsleep -time 10 -locker "/home/agung/.local/bin/lock" -notify 10 -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 10 seconds'" &

exec xidlehook --not-when-fullscreen --timer 610 "systemctl suspend" -
