#!/bin/bash
# scrot '/tmp/%F_%T_$wx$h.png' -e 'xclip -selection clipboard -target image/png -i $f'

output='/home/agung/Pictures/screenshots/%Y-%m-%d-%T-ss.png'

case "$1" in
  "select") scrot "$output" --select --line mode=edge -e "xclip -selection clipboard -target image/png -i $f" || exit ;;
  "select") scrot "$output" --focused --border -e "xclip -selection clipboard -target image/png -i $f" || exit ;;
  *) scrot "$output" || exit ;;
esac

notify-send "Screenshot taken"
sound_screenshot
