#!/bin/bash
#Descriptions: 

dwmblocks &
mpd &
lowbatnotif &
hsetroot -cover /home/agung/Pictures/lago-di-braies-in-the-heart-of-the-dolomites-italy-wallpaper-3840x2560-wallpaper.jpg &
xset r rate 300 50
xset s blank
xset s 300
#picom &
slocker &
dunst &
st -e sudo chown agung:agung /sys/class/backlight/amdgpu_bl0/*
