#!/usr/bin/env bash

# INSTALL DULU I3LOCK-COLOR, CEK DI GITHUB

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot $PICTURE"

BLUR="5x4"

$SCREENSHOT
convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE
rm $PICTURE
