#!/bin/sh

# This is edited from Luke Smith maimpick scripts

case "$(printf "write new note\\nbin\\nxinitrc\\npicom\\nncmpcpp\\nmpd\\nlfrc\\nneovim\\nmpv\\ndunst\\nzsh\\nthis script" | dmenu -l 17 -i -p "Which config to edit?")" in
	"write new note") st -e nvim ~/note-"$(date '+%y%m%d-%H%M-%S').txt" ;;
	"bin") st -e nvim ~/.local/bin/ ;;
	"xinitrc") st -e nvim ~/.xinitrc ;;
	"picom") st -e nvim ~/.config/picom/picom.conf ;;
	"ncmpcpp") st -e nvim ~/.ncmpcpp/config ;;
	"mpd") st -e nvim ~/.mpd/mpd.conf ;;
	"lfrc") st -e nvim ~/.config/lf/lfrc ;;
	"neovim") st -e nvim ~/.config/nvim/init.vim ;;
	"mpv") st -e nvim ~/.config/mpv/mpv.conf ;;
	"dunst") st -e nvim ~/.config/dunst/dunstrc ;;
	"zsh") st -e nvim ~/.zshrc ;;
	"this script") st -e nvim ~/.local/bin/editconfig ;;
esac
