#!/bin/bash

network() {
	wire="$(ip a | grep 'enx00e04c361596' | grep inet | wc -l)"
	wire2="$(ip a | grep 'usb0' | grep inet | wc -l)"
	wifi="$(ip a | grep wlp1s0 | grep inet | wc -l)"

	if [ $wire = 1 ]; then
		   # echo " "
		    echo " ONLINE "
        elif [ $wire2 = 1 ]; then
            #    echo " "
                echo " ONLINE "
	    elif [ $wifi = 1 ]; then
		    #    echo " "
		        echo "ONLINE "
		else
		#	    echo " "
			    echo " OFFLINE "
	fi
}

echo "$(network)"
