#!/bin/bash
#Descriptions: 
#Version: 
#Created Date:  Mon May 2 04:53:41 PM WIB 2022
#Modified Date: 
#By: Agung Satria
# START #
st -c float-st-ncmpcpp -g 60x10+350+200 sudo modprobe -r v4l2loopback
# END #
