#!/bin/bash
#Descriptions: 
#Version: 
#Created Date:  Mon May 2 04:53:41 PM WIB 2022
#Modified Date: 
#By: Agung Satria
# START #
wine ~/.mygithub/dotfiles/usr-share-applications/winbox64.exe
# END #
