#!/bin/sh

# The clickable help menu. Middle click to restart wm.

# If dwm is running, use dwm's readme and restart.
# pidof dwm >/dev/null &&
# 	READMEFILE=/usr/local/share/dwm/larbs.mom
# 	restartwm() { pkill -HUP dwm ;} ||
# 		restartwm() { i3 restart ;}

case $BLOCK_BUTTON in
	1) zathura /home/agung/.dwm/help/help.pdf ;;
	2) notify-send "❓ Help module" "\- Left click to open guide.
- Right click to run rofi" ;;
	3) rofi -modi drun -show drun show-icons true -columns 2 -width 45 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac; echo "❓"
