#!/bin/bash
#Purpose: Execute session optoin after tty login
#Version: -
#Created Date:  Mon 08 Nov 2021 01:24:57 PM WIB
#Modified Date: 
#Author: Agung Satria
# START #
function sessions {
# echo -e "\n Choose your session (Blank=5): \n\c"
# echo -e "\n figlet Choose your session: \n\c"
echo -e "\n"
figlet Choose your session :
# echo -e "\nBlank=5) \c"
echo -e "\ntype "xsessions" (alias=x) to prompt this script) \n\c"
echo -e "\n"
echo "(1) DWM"
echo "(2) Gnome on xorg"
echo "(3) i3"
echo "(4) BSPWM"
echo "(q) Cancel (tty) "
echo "============================================================"
read -r session

if [ "$session" == 1 ]; then 
    cp /home/agung/.xinitrc-temp-dwm-clipboard /home/agung/.xinitrc
    startx
elif [ "$session" == 2 ]; then
    cp /home/agung/.xinitrc-temp-gnome-clipboard /home/agung/.xinitrc
    startx
elif [ "$session" == 3 ]; then
    # cp /home/agung/.xinitrc-temp-i3-clipboard /home/agung/.xinitrc
    # startx
    clear
    echo "Sorry, session not available for now, try another!"
    xsessions
    # return
elif [ "$session" == 4 ]; then
    # cp /home/agung/.xinitrc-temp-bspwm-clipboard /home/agung/.xinitrc
    # startx
    clear
    echo "Sorry, session not available for now, try another!"
    xsessions
    # return
elif [ "$session" == q ]; then 
    return
    # zsh
elif [ -z $session ]; then # -z is jika input blank/kosong
    clear
    echo "No Input"
    xsessions
    # return
    # zsh
else 
    clear
    echo "Wrong Input!"
    xsessions
fi
}
sessions

# END #
